// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iyefaylyitobhupxhnii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5ZWZheWx5aXRvYmh1cHhobmlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MzEzOTcsImV4cCI6MjA2MzIwNzM5N30.rRMakHtAX0r5x2LVkArg6W2N3l0hv0hp-0RVC_iV-iA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);